### PR TITLE
Add logic to python bindings installation

### PR DESCRIPTION
**Pull request by savaroskij**
This PR makes the installation process of python bindings discriminate from unprivileged or privileged users.

### CODE REVIEW

**Review by algebrato — CHANGES_REQUESTED** [review]
Thank you for the suggestion! The idea to introduce the possibility of a local installation for users != root is really good, but personally I would have preferred to see something on CMake level. Something like:
`if (PYTHON_LOCAL_INSTALLATION)`
`COMMAND "${PYTHON_EXE...} --user --site"`
`else(NOT DEFINED PYTHON_LOCAL_INSTALLATION)`
`     COMMAND "${PYTHON_EXE...} -c "import site; print(the_global_path)"`
`endif(PYTHON_LOCAL_INSTALLATION)`

Do you want to try to make this change? I think that could be great!

**Comment by savaroskij** [comment]
I can migrate to a more cmake level solution, but there's no such thing like `PYTHON_LOCAL_INSTALLATION` or `PYTHON_USER_INSTALL` variable. There are at least two possibilities: checking for user ID in a separate cmake command and put  the result in a cmake variable, or domumenting the variable and make the user set it on the command line.
Like this:
```
cmake -D PYTHON_USER_INSTALL=1
``` 

What's better in your opinion?

**Comment by savaroskij** [comment]
The requested changes have been applied and the branch was rebased on them.

**Comment by algebrato** [comment]
Perfect! Squash and merge!

**Pull request merged**
