### PR TITLE
New directory restyling

### PR DESCRIPTION
**Pull request by algebrato**
-) Create a unique include system for mpi and non-mpi libraries;
-) Create a set of unit-tests
-) Improve the documentation
-) !Release weight results!

### CODE REVIEW

**Comment by algebrato** [comment]
The direcotry restyling is completed but, in my opinion, this PR is not ready to be merged in the master branch yet.
Since th restyling was deep, I would like to code some very basically unit test for CAL library in particular:

- [ ] Test the LibAATM wrappers;

- [ ] Test the creation of an atmospheric realization with two different methods
       -[ ] Using the `AtmSim` operator
       -[ ] Using the `AtmSimMPI` operator

**Comment by algebrato** [comment]
**Discussion about the commit 9ffed37 of the PR #15 .** 

The directory restyling is almost completed. With the last commit, I implemented also the generation of the pointing matrix with the quaternion expasion and interpolation. In addiction I implemented also a class `TOD`, in order to split and manage the data in the corret way between different MPI processes. 

@savaroskij  I changed the `__init__` function of the pycal module, in particular:

`import sys`
`import os`
`# from ._libcal import *`
`# from ._libcal_mpi import *`

I commented the total plain importation of all methods and classes. Now, if you want to use the function `atm_atmospheric_loding` you have to import all the `pycal.todmap.atm` submodule in this way:

`from pycal.todmap.atm import *`
`help(atm_atmospheric_load)`

**Comment by savaroskij** [comment]
Thanks @algebrato I'm going to build this branch in a brand new singularity container.

**Comment by savaroskij** [comment]
The `cmake` config pass, but when I try to build I get:

```
In file included from /tmp/cal/src/libcal/src/CALAtmSim.cpp:7:
/tmp/cal/src/libcal/include/cal/CALAtmSim.hpp:13:10: fatal error: sys_env.hpp: No such file or directory
   13 | #include <sys_env.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/libcal/CMakeFiles/calcore.dir/build.make:95: src/libcal/CMakeFiles/calcore.dir/src/CALAtmSim.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:268: src/libcal/CMakeFiles/calcore.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

This error doesn't occur in `master` branch.

My build env:
```
Singularity> uname -a
Linux debian10 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
Singularity> /lib64/libc.so.6 --version
GNU C Library (GNU libc) release release version 2.32.
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 10.2.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
Singularity> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
Singularity> ompi_info -V
Open MPI v4.0.5

http://www.open-mpi.org/community/help/
```

Let me know if you need some more infos.

**Comment by savaroskij** [comment]
The file `sys_env.hpp` is in the same source subdirectory of the file `CALAtmSim.hpp`, so i think i can we can put:

```
#include "sys_env.hpp"
```

instead of:
```
#include <sys_env.hpp>
```

In the include directives. I this way I don't get this error, but a bunch of similar ones.

**Comment by algebrato** [comment]
> The file `sys_env.hpp` is in the same source subdirectory of the file `CALAtmSim.hpp`, so i think i can we can put:
> 
> ```
> #include "sys_env.hpp"
> ```
> 
> instead of:
> 
> ```
> #include <sys_env.hpp>
> ```
> 
> In the include directives. I this way I don't get this error, but a bunch of similar ones.

This issue has just been fixed with commit 9c56924 . I have preferred to mantain the global include structure. I modified the includes directives with `<cal/...>`.

**Comment by savaroskij** [comment]
Thank you very much!
Now this branch just builds flawlessly. The MPI linking problem is solved.
Anyway I'm going to PR this branch with some changes that add some logic to the python bindings installation.

**Pull request merged**
